ENV ?= development
MMA = bundle exec middleman

.PHONY: install
install:
	bundle install
	npm install

.PHONY: build
build:
	$(MMA) build

.PHONY: dev
dev:
	$(MMA) serve

.PHONY: test
test: clean build
	./bin/test

.PHONY: lint
lint:
	bundle exec erb_lint --lint-all

.PHONY: clean
clean:
	rm -rf build

.PHONY: all
all: install clean build test
